version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    restart: always
    container_name: moihub_frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - WHATSAPP_VERIFY_TOKEN=moihub_secreto_123
    restart: always
    container_name: moihub_backend
